import { MD3DarkTheme } from 'react-native-paper';
import { COLORS } from './colors';

export const paperTheme = {
  ...MD3DarkTheme,
  dark: true,
  colors: {
    ...MD3DarkTheme.colors,
    primary: COLORS.primary,
    onPrimary: COLORS.onPrimary,
    primaryContainer: COLORS.primaryContainer,
    onPrimaryContainer: COLORS.onPrimaryContainer,
    secondary: COLORS.secondary,
    onSecondary: COLORS.onSecondary,
    secondaryContainer: COLORS.secondaryContainer,
    onSecondaryContainer: COLORS.onSecondaryContainer,
    tertiary: COLORS.tertiary,
    onTertiary: COLORS.onTertiary,
    tertiaryContainer: COLORS.tertiaryContainer,
    onTertiaryContainer: COLORS.onTertiaryContainer,
    error: COLORS.error,
    onError: COLORS.onError,
    errorContainer: COLORS.errorContainer,
    onErrorContainer: COLORS.onErrorContainer,
    background: COLORS.background,
    onBackground: COLORS.onBackground,
    surface: COLORS.surface,
    onSurface: COLORS.onSurface,
    surfaceVariant: COLORS.surfaceVariant,
    onSurfaceVariant: COLORS.onSurfaceVariant,
    outline: COLORS.outline,
    outlineVariant: COLORS.outlineVariant,
    shadow: COLORS.shadow,
    scrim: COLORS.scrim,
    inverseSurface: COLORS.inverseSurface,
    inverseOnSurface: COLORS.inverseOnSurface,
    inversePrimary: COLORS.inversePrimary,
    surfaceDim: COLORS.surfaceDim,
    surfaceBright: COLORS.surfaceBright,
    surfaceContainerLowest: COLORS.surfaceContainerLowest,
    surfaceContainerLow: COLORS.surfaceContainerLow,
    surfaceContainer: COLORS.surfaceContainer,
    surfaceContainerHigh: COLORS.surfaceContainerHigh,
    surfaceContainerHighest: COLORS.surfaceContainerHighest,
  },
};
